name: doracle
description: "A new Flutter project."
publish_to: "none"
version: 99.99.99+99
environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_messaging: ^15.0.3
  firebase_crashlytics: ^4.0.3
  firebase_analytics: ^11.2.0
  firebase_app_check: ^0.3.0+3
  cloud_firestore: ^5.1.0
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1
  dart_openai: ^5.1.0
  purchases_flutter: ^6.29.4
  get_it: ^7.7.0
  auto_size_text: ^3.0.0
  carousel_slider: ^4.2.1
  shake: ^2.2.0
  font_awesome_flutter: ^10.7.0
  rive: ^0.13.9
  in_app_review: ^2.0.9
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  haptic_feedback: ^0.5.1+1
  eraser: ^2.0.2
  typewritertext: ^3.0.8
  characters: ^1.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  sensors_plus: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/background.png
    - assets/images/doracle_logo_1@2x.webp
    - assets/images/doracle2.png
    - assets/images/paw.png
    - assets/animations/meraki_dog_rev5.riv

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon_v2.png"
  remove_alpha_ios: true
