name: doracle
description: "Doracle - Your Personal Oracle"
publish_to: "none"
version: 99.99.99+99
environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Attribution and analytics

  # Firebase dependencies - updated to latest versions
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_messaging: ^15.2.4
  firebase_crashlytics: ^4.3.4
  firebase_analytics: ^11.4.4
  firebase_app_check: ^0.3.2+4
  cloud_firestore: ^5.6.5
  
  # Meta/Facebook marketing
  facebook_app_events: ^0.19.5
  
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.7.0
  google_places_autocomplete_text_field: ^0.1.3
  dart_openai: ^5.1.0
  purchases_flutter: ^6.29.4
  get_it: ^7.7.0
  auto_size_text: ^3.0.0
  carousel_slider: ^5.0.0
  shake: ^2.2.0
  font_awesome_flutter: ^10.7.0
  rive: ^0.13.9
  in_app_review: ^2.0.9
  share_plus: ^7.2.2
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  haptic_feedback: ^0.5.1+1
  eraser: ^2.0.2
  typewritertext: ^3.0.8
  characters: ^1.3.0
  scrollable: ^1.0.5
  uuid: ^4.4.2
  geocoding: ^3.0.0
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.2.0+3
  flutter_animate: ^4.5.0
  styled_divider: ^1.0.5
  provider: ^6.1.2
  flutter_keyboard_visibility: ^6.0.0
  device_info_plus: ^10.1.2
  adjust_sdk: ^5.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  sensors_plus: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/animations/
  fonts:
    - family: doracle
      fonts:
        - asset: assets/fonts/doracle.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon_v2.png"
  remove_alpha_ios: true
