name: fortuntella
description: "A new Flutter project."
publish_to: "none"
version: 99.99.99+99
environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_crashlytics: ^4.0.2
  firebase_analytics: ^11.1.0
  firebase_app_check: ^0.3.0+2
  cloud_firestore: ^5.0.1
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.0
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.3
  dart_openai: ^5.1.0
  rive: ^0.13.8
  purchases_flutter: ^6.29.4
  get_it: ^7.7.0
  auto_size_text: ^3.0.0
  carousel_slider: ^4.2.1
  shake: ^2.2.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  sensors_plus: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/splash/background.png
    - assets/images/google_logo.png
    - assets/images/apple_logo.png
    - assets/images/paw.png
    - assets/animations/meraki_dog.riv

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/doracle_logo.png"
  remove_alpha_ios: true
