name: fortuntella
description: "A new Flutter project."
publish_to: "none"
version: 99.99.99+99
environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.0
  cloud_firestore: ^5.0.1
  google_sign_in: ^6.2.1
  http: ^1.2.1
  dart_openai: ^5.1.0
  google_generative_ai: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/splash/background.png
    - assets/google_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  remove_alpha_ios: true
