# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

# Modify the facebook_app_events.podspec file to use FBAudienceNetwork 6.17.0
podspec_path = File.join(File.dirname(__FILE__), '.symlinks', 'plugins', 'facebook_app_events', 'ios', 'facebook_app_events.podspec')
if File.exist?(podspec_path)
  puts "Modifying #{podspec_path} to use FBAudienceNetwork 6.17.0"
  podspec_content = File.read(podspec_path)
  modified_content = podspec_content.gsub("s.dependency 'FBAudienceNetwork', '6.16'", "s.dependency 'FBAudienceNetwork', '6.17.0'")
  File.write(podspec_path, modified_content)
  puts "Successfully modified facebook_app_events.podspec"
else
  puts "Warning: Could not find facebook_app_events.podspec at #{podspec_path}"
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Include FirebaseCrashlytics in all configurations to support development builds
  pod 'FirebaseCrashlytics'
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '11.8.0'
  
  # Explicitly specify FBAudienceNetwork version as a direct dependency
  pod 'FBAudienceNetwork', '6.17.0'
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # You can remove unused permissions here
      # for more information: https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',        
        ## dart: PermissionGroup.notification
        'PERMISSION_NOTIFICATIONS=1',
        ## dart: PermissionGroup.appTrackingTransparency
        'PERMISSION_APP_TRACKING_TRANSPARENCY=1',
      ]

      # Only essential setting to fix Firebase non-modular headers issue
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      
      # Force all Pods to use at least iOS 14.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      
      # Add Swift linking flags to fix Swift symbol errors
      if target.name == 'Runner' || target.name.include?('facebook') || target.name.include?('FBAudienceNetwork')
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = [
          '$(inherited)',
          '@executable_path/Frameworks'
        ]
        
        # Add Swift standard libraries
        config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
      end
    end
  end
end
