name: IOS Pipeline

on: #workflow_dispatch
  push:
    branches:
      - main

jobs:
  build-and-deploy-ios:
    runs-on: macos-latest
    steps:
      - name: Set up git and fetch all history for all branches and tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract .env variable
        run: |
          echo "${{secrets.RELEASE_ENV}}" > .env.asc
          echo "${{secrets.RELEASE_GOOGLEPLIST}}" > GoogleService-Info.plist.asc
          gpg -d --passphrase "${{secrets.RELEASE_ENV_PASSWORD}}" --batch .env.asc > .env
          gpg -d --passphrase "${{secrets.RELEASE_GOOGLEPLIST_PASSWORD}}" --batch GoogleService-Info.plist.asc > ios/Runner/GoogleService-Info.plist
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - name: Bundle install for iOS Gemfile
        timeout-minutes: 5
        run: cd ./ios && bundle install
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
          channel: "stable"
          architecture: x64
          cache: true
      - name: Build and Deploy to TestFlight
        id: build_deploy
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8: ${{ secrets.ASC_KEY_P8 }}
        run: |
          cd ./ios
          bundle exec fastlane release_beta
      - name: Send an AAB link to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{vars.CHANNEL_ID}}
          slack-message: " You can test <itms-beta://testflight.apple.com/v1/app/6504555731|Testflight> [*${{steps.build_deploy.outputs.VERSION_NUMBER}}* (${{steps.build_deploy.outputs.BUILD_NUMBER}})] "
        env:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
